### ISSUE TITLE
Commands throw an error

### ISSUE THREAD

**Issue by Regitus** [Selsion/DSPMods#1]
When using -checkMask or -resetMask I get this error message:
It is about the AbnormalityParser. 
>> -<color="yellow">checkMask</color>
>> An error has occured 
<color="#ff4040">System.TypeLoadException: Could not resolve type with token 0100001e (from typeref, class/assembly GameAbnormalityCheck, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
  at AbnormalityParser.AbnormalityParser.CheckMask (System.String param) [0x0000c] in <3599d7f7cfab4a41aa7677fe8975a488>:0 
  at XConsole.ExecuteCommand (System.String cmd) [0x00189] in <8be0b94ee4174803af906bc5fe28296c>:0

Did I do something wrong or is it the newest DSP Update?

**Comment by Selsion** [comment]
Thanks for notifying me of the error. The abnormality detection system had a rework with one of the newest updates, which broke the mod's commands. I'll have to rewrite the mod. Fortunately, it looks like the new system logs detailed info on detected abnormalities, so I should be able to add commands that give much more information than before.

**Comment by Selsion** [comment]
Fixed in [#f27a1bb ](https://github.com/Selsion/DSPMods/commit/f27a1bbc34e6e0dd23ff1a4efb1b71c27494228d)
