### ISSUE TITLE
Can't work with XGP version

### ISSUE THREAD

**Issue by e-legy** [Selsion/DSPMods#8]
`[Warning:   BepInEx] Skipping [DSPOptimizations 1.1.16] because of process filters (DSPGAME.exe)`
it seems to skip xgp game process(Dyson Sphere Program.exe)

**Comment by Selsion** [comment]
Sorry about forgetting about this for a while. I removed the process filter in v1.1.17 of DSPOptimizations, so this issue should be fixed.
